# Generated by Django 2.0.5 on 2018-05-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20180531_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='work',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
