# Generated by Django 2.0.5 on 2018-05-31 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180531_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
