# Generated by Django 2.0.5 on 2018-05-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20180531_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='Category',
            new_name='category',
        ),
    ]
