# Generated by Django 2.0.5 on 2018-05-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20180531_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='text',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='blogcomment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='text',
            new_name='description',
        ),
    ]
