# Generated by Django 2.0.5 on 2018-05-31 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20180531_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pricing',
            old_name='rate',
            new_name='amount',
        ),
        migrations.AlterField(
            model_name='numbers',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
