# Generated by Django 2.0.5 on 2018-05-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180531_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RenameField(
            model_name='team',
            old_name='facebook',
            new_name='facebook_url',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='google',
            new_name='google_url',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='twitter',
            new_name='twitter_url',
        ),
    ]
