# Generated by Django 2.0.5 on 2018-06-01 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180531_1234'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='')),
                ('contact_title', models.CharField(max_length=255)),
                ('contact_detail', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HomeCustomization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_top', models.ImageField(upload_to='')),
                ('logo_bottom', models.ImageField(upload_to='')),
                ('banner_heading', models.CharField(max_length=255)),
                ('banner_text', models.TextField()),
                ('welcome_note', models.CharField(max_length=255)),
                ('featured_works_heading', models.CharField(max_length=255)),
                ('services_heading', models.CharField(max_length=255)),
                ('why_choose_us_heading', models.CharField(max_length=255)),
                ('why_choose_us_text', models.TextField()),
                ('pricing_table_heading', models.CharField(max_length=255)),
                ('our_team_heading', models.CharField(max_length=255)),
                ('recent_news_heading', models.CharField(max_length=255)),
                ('get_in_touch_heading', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SendMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='WebSite',
        ),
    ]
