# Generated by Django 2.0.5 on 2018-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20180601_0657'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterSocial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.URLField()),
                ('url', models.URLField()),
            ],
        ),
    ]
