# Generated by Django 2.0.5 on 2018-06-05 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_footersocial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footersocial',
            name='icon',
            field=models.ImageField(upload_to=''),
        ),
    ]
