# Generated by Django 2.0.5 on 2018-06-05 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20180605_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='footersocial',
            name='title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
